In [1]:
import pandas as pd

In [2]:
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[0])
print(s[1])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
2

In [3]:
s=pd.Series([23,12,24,52],index=["Adam","Ram","Hari","Hero"])
print(s)
print(s['Adam'])
print(s["Hari"])
print(s[1])
print(s.index)

Adam    23
Ram     12
Hari    24
Hero    52
dtype: int64
23
24
12
Index(['Adam', 'Ram', 'Hari', 'Hero'], dtype='object')

/var/folders/wf/bm25hvvn46s6x72gggcqvm380000gn/T/ipykernel_59436/1365196873.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

## Ways of creating  DataFrame

In [4]:
s1=pd.Series([2,3,5,3,2])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)

s1[0]=100
changed_s1=s1.drop(0)
print(s1)
print(changed_s1)

0    12
1    23
2    35
3    43
4    52
dtype: int64
0    100
1      3
2      5
3      3
4      2
dtype: int64
1    3
2    5
3    3
4    2
dtype: int64

In [5]:
info={
    "Name":["Ram","Jenisha","Abhesh"],
    "Age":[20,17,19],
    "CGPA":[9,10,8]
}
df=pd.DataFrame(info)
print(df,type(df))
print(df.index)
print(df.columns)

      Name  Age  CGPA
0      Ram   20     9
1  Jenisha   17    10
2   Abhesh   19     8 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [6]:

import numpy as np 
np_arr=np.array([[1,2,3],[4,5,6]]) 
df=pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [7]:
# csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [8]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

## DataFrames Methods

In [9]:
#Methods
# Display the first 5 rows of the DataFrame
df.head()

# Display the last 5 rows of the DataFrame
df.tail()

# Display a random row (or random rows if n is specified)
df.sample()

# Show a concise summary of the DataFrame
# (column names, data types, non-null counts, memory usage)
df.info()

# Return the dimensions of the DataFrame as (rows, columns)
df.shape

# Generate descriptive statistics for numerical columns
# (count, mean, std, min, 25%, 50%, 75%, max)
df.describe()

# Display all column names in the DataFrame
df.columns

# Count the number of unique values in each column
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [10]:
df=pd.read_csv('globalAirQuality.csv')
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [11]:
#selecting methods

#columns
df["city"]
df[["city","aqi"]]

#rows
df.loc[2]
df.loc[0:2] #start index : ending index (inclusive)

df.iloc[2]
df.iloc[0:2]  #start index : ending index (exclusive)

#cells -row,col
df.loc[0,['city','aqi']]
df.columns
df.loc[0,['city','aqi']]
df.iloc[0:3,2]
df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]


cities=df["city"].copy()
cities[0]="New York"
cities

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [12]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [44]:
#filtering of data
# Filter rows where AQI (Air Quality Index) is greater than 100
df[df["aqi"] > 100]

# Filter rows where AQI is greater than 100 and temperature is above 30°C
df[(df["aqi"] > 100) & (df["temperature"] > 30)]

# Filter rows where AQI is greater than 100 and temperature is below 30°C
df[(df["aqi"] > 100) & (df["temperature"] < 30)]

# Create a new DataFrame containing only the city and AQI columns
# for locations where AQI > 100 and temperature > 30°C
aqi = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

# Retrieve the first row of the filtered DataFrame using integer position
aqi.iloc[0]

# Retrieve the row with index label 6 from the filtered DataFrame
aqi.loc[6]

#Query -- copy
aqi_val=100
df.query("aqi>100 & temperature>30")[["city","aqi"]]
aqi_data=df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]].copy()

In [29]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403